server:
  port: 52000
spring:
  application:
    name: generate-code-tool
  datasource:
    url: jdbc:mysql://localhost:3306/generate_code?characterEncoding=utf-8&useSSL=false
    username: root
    password: lzlg520llx
